# Generated by Django 4.0.6 on 2022-07-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contrador'), ('1', 'Administrador'), ('2', 'Economista'), ('4', 'Otro')], max_length=20, verbose_name='Trabajo'),
        ),
    ]
